### ISSUE TITLE
Add background/fill color for outline icons

### ISSUE THREAD

**Issue by prateekmedia** [TesteurManiak/icon_decoration#1]
There are various icon packs like [`lucide_icons`](https://pub.dev/packages/lucide_icons) which only supply outlined icon which is good, but If I want a filled star or a liked heart(filled) then it won't be possible with bare flutter.

If we can fill those outlined icons then this would become a very useful package as we can already add borders to an icon.

**Comment by TesteurManiak** [comment]
While I understand the interest for such a feature, I don't think it is realizable without re-implementing entirely the way `RichText` is painted. As mentionned in the [Flutter Icon widget documentation](https://api.flutter.dev/flutter/widgets/Icon-class.html):
> This widget assumes that the rendered icon is squared.

Which means that it is not aware of the icon's real shape. I've tested by using the `backgroundColor` property of `TextStyle` and this is the result:
![basic_red_background](https://user-images.githubusercontent.com/14369698/137471251-ac2942d8-8d10-4e24-8a61-a06592a6ecee.png)

As you can see the background is rendered inside a square without consideraing the shape of the icon and the `TextStyle` API does not provide a way to clip or customize the path of the background.

**Comment by prateekmedia** [comment]
How do you draw the border then?
