### ISSUE TITLE
IconDecoration's gradient property doesn't work anymore

### ISSUE THREAD

**Issue by MeixDev** [TesteurManiak/icon_decoration#3]
Hi!

The package was working fine last time I tested it a few months ago, but it now seems to be incapable of rendering any gradients. It seems the last color used in the gradient is the one used to paint the whole widget.

**Comment by TesteurManiak** [comment]
I've been able to reproduce this bug with the following test:

## Code

```dart
void main() {
  group('Goldens Issue #3', () {
    goldenTest(
      "IconDecoration's gradient property doesn't work anymore",
      fileName: 'issue_3',
      widget: GoldenTestGroup(
        children: [
          GoldenTestScenario(
            name: 'with rainbow gradient',
            child: const DecoratedIcon(
              icon: Icon(Icons.all_inbox, size: 50),
              decoration: IconDecoration(
                gradient: rainbowGradient,
              ),
            ),
          ),
          GoldenTestScenario(
            name: 'same rainbow gradient',
            child: const DecoratedIcon(
              icon: Icon(Icons.all_inbox, size: 50),
              decoration: IconDecoration(
                gradient: rainbowGradient,
              ),
            ),
          ),
        ],
      ),
    );
  });
}
```

## Golden

![issue_3](https://user-images.githubusercontent.com/14369698/157821461-9dd7300c-d372-43e3-8dbf-8dec0e10ee18.png)

Seems like it is an issue with the gradient's boundaries when creating the shader for the gradient:

```dart
if (gradient != null) {
  iconStyle = iconStyle.copyWith(
    foreground: Paint()
      ..shader = gradient.createShader(
        Rect.fromLTWH(0, 0, iconSize, iconSize),
      ),
  );
}
```

**Comment by TesteurManiak** [comment]
I've created a custom widget to render Icon with a gradient, it might change a bit the way a gradient is rendered because now that the boundaries are correct.

All related test can be found in `gradient_test.dart`, you should obtain a result similar to this:

![gradient_rendering](https://user-images.githubusercontent.com/14369698/157835652-3938c45b-1226-4315-bb4a-24467b110abb.png)
